services:
  postgres-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_ID: 1000
        GROUP_ID: 1000
    container_name: postgres-service-db
    shm_size: '5gb'
    mem_limit: 16g
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/pgsql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf:ro

networks:
  default:
    name: postgres_network

volumes:
  postgres_data:
